create table app_user
(
    user_id integer generated by default as identity
        constraint appUsers_pkey
            primary key,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    email varchar(255) not null unique,
    profile_name varchar(255) not null,
    password varchar(255) not null,
    role varchar(255)
);
