create table accounts
(
    account_id integer generated by default as identity
        constraint accounts_pkey
            primary key,
    password varchar(255),
    email varchar(255)
        constraint uk_n7ihswpy07ci568w34q0oi8he
            unique,
    role varchar(255)
);
