create table codecoach.topics
(
    topic_id int generated by default as identity
        constraint topics_pk
            primary key,
    name varchar(255)
);

create table codecoach.user_topics
(
    user_id int
        constraint user_topics_user_id_fk
            references codecoach.app_user
            on delete cascade,
    topic_id int
        constraint user_topics_topic_id_fk
            references codecoach.topics (topic_id)
            on delete cascade,
    constraint user_topics_pk
        primary key (topic_id, user_id)
);