name: Test

on: push

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      #      - run: sed -ri 's/gertjan/fred-test/g' ./src/main/resources/application.properties
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - run: mvn clean install